## Transformações Lineares

Transformações lineares são funções que mapeiam vetores de um espaço vetorial para outro (ou para ele mesmo), preservando as operações de adição de vetores e multiplicação por escalares. Em outras palavras, se \(T\) é uma transformação linear, então para todos os vetores \( \mathbf{u} \) e \( \mathbf{v} \) e escalar \(c\), temos:

1. T(u+v) = T(u) + T(v)
2. T(cu)=cT(u)

#### Propriedades das Transformações Lineares:
1. **Linearidade**: Como mostrado acima, transformações lineares mantêm a adição de vetores e a multiplicação por escalares.
2. **Representação por Matrizes**: Qualquer transformação linear pode ser representada por uma matriz. A aplicação da transformação a um vetor é realizada pela multiplicação da matriz pela coluna que representa o vetor.
3. **Transformações Geométricas**: Incluem rotações, reflexões, expansões, contrações e cisalhamentos (shear).

#### Exemplos de Transformações Lineares:
- **Rotação**: Rotaciona um vetor em um certo ângulo.
- **Reflexão**: Reflete um vetor em relação a um eixo.
- **Escala**: Aumenta ou diminui o comprimento de um vetor por um fator constante.
- **Cisalhamento (Shear)**: Desloca os pontos ao longo de um eixo em proporção a suas distâncias de outro eixo.


In [3]:
import numpy as np

# Função para aplicar transformação e mostrar resultado
def apply_transformation(T, vectors):
    transformed_vectors = np.dot(T, vectors)
    print("Transformação aplicada:")
    print(transformed_vectors)

# Vetores a serem transformados (colunas da matriz)
vectors = np.array([[1, 0], [0, 1]])  # Vetores unitários na base padrão

In [4]:
# 1. Rotação de 90 graus
theta = np.pi / 2  # Ângulo em radianos
rotation_matrix = np.array([[np.cos(theta), -np.sin(theta)], 
                            [np.sin(theta), np.cos(theta)]])
print("Matriz de Rotação de 90 graus:")
print(rotation_matrix)
apply_transformation(rotation_matrix, vectors)

Matriz de Rotação de 90 graus:
[[ 6.123234e-17 -1.000000e+00]
 [ 1.000000e+00  6.123234e-17]]
Transformação aplicada:
[[ 6.123234e-17 -1.000000e+00]
 [ 1.000000e+00  6.123234e-17]]


In [5]:
# 2. Reflexão em relação ao eixo x
reflection_matrix = np.array([[1, 0], 
                            [0, -1]])
print("\nMatriz de Reflexão em relação ao eixo x:")
print(reflection_matrix)
apply_transformation(reflection_matrix, vectors)


Matriz de Reflexão em relação ao eixo x:
[[ 1  0]
 [ 0 -1]]
Transformação aplicada:
[[ 1  0]
 [ 0 -1]]


In [6]:
# 3. Escala por um fator de 2
scaling_matrix = np.array([[2, 0], 
                        [0, 2]])
print("\nMatriz de Escala por um fator de 2:")
print(scaling_matrix)
apply_transformation(scaling_matrix, vectors)


Matriz de Escala por um fator de 2:
[[2 0]
 [0 2]]
Transformação aplicada:
[[2 0]
 [0 2]]


In [7]:
# 4. Cisalhamento (Shear) horizontal
shear_matrix = np.array([[1, 1], 
                        [0, 1]])
print("\nMatriz de Cisalhamento horizontal:")
print(shear_matrix)
apply_transformation(shear_matrix, vectors)


Matriz de Cisalhamento horizontal:
[[1 1]
 [0 1]]
Transformação aplicada:
[[1 1]
 [0 1]]
