## Álgebra Linear

Álgebra Linear é um ramo da matemática que estuda espaços vetoriais, transformações lineares e sistemas de equações lineares. Aqui estão alguns conceitos chave de forma didática:

1. **Espaços Vetoriais**: Um espaço vetorial é um conjunto de objetos (vetores) que podem ser somados entre si e multiplicados por escalares (números), satisfazendo certas propriedades. Por exemplo, os vetores geométricos que você aprende em física ou matemática são um tipo de vetor.

2. **Transformações Lineares**: São regras ou funções que preservam a estrutura vetorial, ou seja, levam vetores de um espaço vetorial para outro de maneira consistente. Por exemplo, uma rotação ou uma dilatação são transformações lineares em certos contextos.

3. **Sistemas de Equações Lineares**: São conjuntos de equações onde cada equação é linear (os termos são somas de constantes multiplicadas por variáveis). Resolver esses sistemas significa encontrar valores das variáveis que satisfazem todas as equações simultaneamente.

4. **Matrizes**: São tabelas retangulares de números que representam transformações lineares, sistemas de equações e outras operações em Álgebra Linear. Elas são essenciais para resolver sistemas lineares e descrever transformações geométricas.

5. **Determinantes**: São números associados a matrizes quadradas que ajudam a determinar se uma matriz é invertível e a calcular volumes em geometria.

6. **Autovalores e Autovetores**: São conceitos avançados que descrevem propriedades especiais de transformações lineares, indicando direções especiais (autovetores) e escalas (autovalores) que permanecem inalteradas sob essas transformações.

Álgebra Linear tem muitas aplicações em física, engenharia, ciência da computação, economia e em muitos outros campos, sendo fundamental para modelar e resolver uma ampla variedade de problemas quantitativos.

## Matrizes

Matrizes são tabelas retangulares de números organizados em linhas e colunas. Elas são fundamentais na Álgebra Linear e têm várias aplicações em diversas áreas, como física, engenharia, economia e ciência da computação. Aqui estão os pontos principais de forma didática:

1. **Estrutura**: Uma matriz é uma coleção ordenada de números dispostos em linhas e colunas. Por exemplo, uma matriz 2x3 tem 2 linhas e 3 colunas.

2. **Elementos**: Cada número na matriz é chamado de elemento. Eles são identificados pela sua posição, usando o número da linha seguido do número da coluna. Por exemplo, o elemento na segunda linha e terceira coluna é denotado como \( A_{2,3} \).

3. **Tipos de Matrizes**:
   - **Matriz Quadrada**: Tem o mesmo número de linhas e colunas.
   - **Matriz Retangular**: Tem um número diferente de linhas e colunas.
   - **Matriz de Linha e Coluna**: Tem apenas uma linha ou uma coluna.

4. **Operações Básicas**:
   - **Adição e Subtração**: Matrizes do mesmo tamanho podem ser somadas ou subtraídas, adicionando ou subtraindo elementos correspondentes.
   - **Multiplicação por Escalar**: Cada elemento da matriz é multiplicado por um número (escalar).
   - **Multiplicação de Matrizes**: A multiplicação de duas matrizes é definida se o número de colunas da primeira matriz é igual ao número de linhas da segunda matriz.

5. **Aplicações**:
   - **Sistemas de Equações Lineares**: Matrizes são usadas para representar e resolver sistemas de equações lineares.
   - **Transformações Geométricas**: Em geometria, matrizes representam transformações como rotações, escalas e reflexões.
   - **Computação Gráfica**: São essenciais para representar objetos 3D, realizar projeções e animações.
   - **Redes Neurais**: São usadas para calcular operações de peso em camadas de redes neurais artificiais.

Matrizes são uma ferramenta poderosa para organizar dados e resolver problemas complexos em diversas áreas do conhecimento, tornando-se uma parte fundamental da matemática aplicada e da ciência da computação.

### Matrizes no Python

Em Python uma matriz poder ser apresentada como uma lista de listas, onde cada lista interna representa uma linha da matriz, que por sua vez corresponde a uma lista com os elementos da coluna da matriz. Por exemplo, para criar uma matriz 2 por 3, podemos usar a seguinte sintaxe:

In [2]:
matriz_A = [[1, 2, 3], [4, 5, 6]]

matriz_A

[[1, 2, 3], [4, 5, 6]]

In [5]:
matriz_A[0][1]

2

Usar listas aninhadas como matriz funciona para tarefas computacionais simples. No entanto, existe uma maneira melhor de trabalhar
com matrizes em Python usando o pacote NumPy.

In [1]:
import numpy as np

matriz_B = np.array([[1, 2, 3], [4, 5, 6], [7, 8,9]])

matriz_B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
# Transposição de Matriz

matriz_transposta = matriz_B.transpose()
matriz_transposta

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [3]:
# Adição de Matrizes

matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

matriz1 + matriz2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [4]:
# Multiplicação de Matrizes

matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

np.dot(matriz1, matriz2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])