## Determinantes

Os determinantes são números que podem ser calculados a partir de matrizes quadradas (mesmo número de linhas e colunas). Eles fornecem informações importantes sobre a matriz e têm diversas aplicações em álgebra linear, como verificar se uma matriz é invertível ou calcular volumes em geometria.

#### Propriedades dos Determinantes:
1. **Invertibilidade**: Uma matriz é invertível (ou não singular) se e somente se o seu determinante é diferente de zero.
2. **Área e Volume**: Em 2D, o determinante de uma matriz 2x2 representa a área de um paralelogramo formado pelos vetores das colunas da matriz. Em 3D, ele representa o volume de um paralelepípedo.
3. **Transformações Lineares**: O determinante de uma matriz que representa uma transformação linear indica o fator pelo qual áreas ou volumes são escalados pela transformação.

#### Cálculo de Determinantes:
- Para uma matriz 2x2:
  ```
  |A| = |a b|
        |c d|
        
  det(A) = ad - bc
  ```
- Para uma matriz 3x3:
  ```
  |A| = |a b c|
        |d e f|
        |g h i|
        
  det(A) = a(ei - fh) - b(di - fg) + c(dh - eg)
  ```


In [2]:
# Matriz 2x2

import numpy as np

A_2x2 = np.array([[1, 2], [3, 4]])
det_A_2x2 = np.linalg.det(A_2x2)
print("Matriz 2x2 (A):")
print(A_2x2)
print("Determinante de A:", det_A_2x2)

Matriz 2x2 (A):
[[1 2]
 [3 4]]
Determinante de A: -2.0000000000000004


In [3]:
# Matriz 3x3
A_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
det_A_3x3 = np.linalg.det(A_3x3)
print("\\nMatriz 3x3 (A):")
print(A_3x3)
print("Determinante de A:", det_A_3x3)

\nMatriz 3x3 (A):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinante de A: -9.51619735392994e-16


In [4]:
# Verificação de invertibilidade
if det_A_2x2 != 0:
    print("\\nA matriz 2x2 é invertível.")
else:
    print("\\nA matriz 2x2 não é invertível.")

if det_A_3x3 != 0:
    print("\\nA matriz 3x3 é invertível.")
else:
    print("\\nA matriz 3x3 não é invertível.")


\nA matriz 2x2 é invertível.
\nA matriz 3x3 é invertível.
