## Matrizes Especiais

Matrizes especiais são matrizes com características particulares que facilitam sua manipulação e aplicação em diversos problemas. Aqui estão alguns dos tipos mais importantes:

1. **Matriz Identidade (I)**:
   - **Descrição**: Uma matriz quadrada com 1's na diagonal principal (do canto superior esquerdo ao canto inferior direito) e 0's em todos os outros lugares.
   - **Propriedade**: Multiplicar qualquer matriz pela matriz identidade resulta na matriz original.
   - **Exemplo**:
     ```
     I = [1 0]
         [0 1]
     ```

2. **Matriz Diagonal**:
   - **Descrição**: Uma matriz onde todos os elementos fora da diagonal principal são zero.
   - **Propriedade**: Fácil de inverter e elevar a potências.
   - **Exemplo**:
     ```
     D = [3 0]
         [0 5]
     ```

3. **Matriz Nula (ou Zero)**:
   - **Descrição**: Todos os elementos são zero.
   - **Propriedade**: A adição da matriz nula a qualquer outra matriz não altera a matriz original.
   - **Exemplo**:
     ```
     O = [0 0]
         [0 0]
     ```

4. **Matriz Transposta (A^T)**:
   - **Descrição**: Obtida trocando as linhas e colunas de uma matriz.
   - **Propriedade**: A transposta da transposta de uma matriz é a matriz original.
   - **Exemplo**: Se A = [1 2] [3 4], então A^T = [1 3] [2 4].

5. **Matriz Simétrica**:
   - **Descrição**: Uma matriz quadrada que é igual à sua transposta (A = A^T).
   - **Propriedade**: Seus autovalores são reais.
   - **Exemplo**:
     ```
     S = [1 2]
         [2 3]
     ```

6. **Matriz Anti-Simétrica (ou Skew-Simétrica)**:
   - **Descrição**: Uma matriz quadrada onde A^T = -A.
   - **Propriedade**: Os elementos da diagonal principal são zero.
   - **Exemplo**:
     ```
     A = [ 0 -2]
         [ 2  0]
     ```

7. **Matriz Ortogonal**:
   - **Descrição**: Uma matriz quadrada cujas linhas e colunas são vetores ortonormais (A^T A = I).
   - **Propriedade**: Preserva distâncias e ângulos em transformações.
   - **Exemplo**:
     ```
     Q = [ 1  0]
         [ 0 -1]
     ```

8. **Matriz Triangular**:
   - **Descrição**: Pode ser triangular superior (todos os elementos abaixo da diagonal principal são zero) ou triangular inferior (todos os elementos acima da diagonal principal são zero).
   - **Propriedade**: Facilita a resolução de sistemas lineares.
   - **Exemplo**:
     ```
     Triangular Superior:
     [1 2]
     [0 3]
     
     Triangular Inferior:
     [4 0]
     [2 5]
     ```


In [1]:
import numpy as np

# 1. Matriz Identidade
I = np.eye(2)
print("Matriz Identidade (I):")
print(I)

Matriz Identidade (I):
[[1. 0.]
 [0. 1.]]


In [2]:
# 2. Matriz Diagonal
D = np.diag([3, 5])
print("\nMatriz Diagonal (D):")
print(D)


Matriz Diagonal (D):
[[3 0]
 [0 5]]


In [3]:
# 3. Matriz Nula (ou Zero)
O = np.zeros((2, 2))
print("\nMatriz Nula (O):")
print(O)


Matriz Nula (O):
[[0. 0.]
 [0. 0.]]


In [4]:
# 4. Matriz Transposta
A = np.array([[1, 2], [3, 4]])
A_T = A.T
print("\nMatriz A:")
print(A)
print("Matriz Transposta (A^T):")
print(A_T)


Matriz A:
[[1 2]
 [3 4]]
Matriz Transposta (A^T):
[[1 3]
 [2 4]]


In [5]:
# 5. Matriz Simétrica
S = np.array([[1, 2], [2, 3]])
print("\nMatriz Simétrica (S):")
print(S)


Matriz Simétrica (S):
[[1 2]
 [2 3]]


In [6]:
# 6. Matriz Anti-Simétrica (ou Skew-Simétrica)
A_skew = np.array([[0, -2], [2, 0]])
print("\nMatriz Anti-Simétrica (A_skew):")
print(A_skew)


Matriz Anti-Simétrica (A_skew):
[[ 0 -2]
 [ 2  0]]


In [7]:
# 7. Matriz Ortogonal
Q = np.array([[1, 0], [0, -1]])
print("\nMatriz Ortogonal (Q):")
print(Q)
print("Verificação (Q^T Q):")
print(Q.T @ Q)


Matriz Ortogonal (Q):
[[ 1  0]
 [ 0 -1]]
Verificação (Q^T Q):
[[1 0]
 [0 1]]


In [8]:
# 8. Matriz Triangular
# Triangular Superior
U = np.array([[1, 2], [0, 3]])
# Triangular Inferior
L = np.array([[4, 0], [2, 5]])
print("\nMatriz Triangular Superior (U):")
print(U)
print("Matriz Triangular Inferior (L):")
print(L)


Matriz Triangular Superior (U):
[[1 2]
 [0 3]]
Matriz Triangular Inferior (L):
[[4 0]
 [2 5]]
