O NumPy é uma biblioteca popular em Python usada principalmente para trabalhar com arrays multidimensionais e funções matemáticas que operam nesses arrays.

1. **Arrays NumPy**: Pense em arrays como uma coleção de elementos, semelhante a listas em Python, mas com capacidade de lidar com operações matemáticas de forma eficiente em grandes conjuntos de dados. Os arrays NumPy podem ter uma ou várias dimensões (como uma matriz).

2. **Eficiência**: O NumPy é construído em C, o que o torna muito rápido e eficiente em comparação com as listas Python padrão, especialmente quando lidamos com grandes conjuntos de dados.

3. **Funcionalidades matemáticas**: O NumPy oferece um conjunto abrangente de funções matemáticas que podem ser aplicadas aos arrays, incluindo operações básicas (como adição, subtração, multiplicação e divisão), funções trigonométricas, operações de álgebra linear, estatísticas e muito mais.

4. **Indexação e fatiamento**: Assim como as listas em Python, os arrays NumPy podem ser indexados e fatiados para acessar elementos individuais ou subconjuntos de elementos.

5. **Broadcasting**: Essa é uma funcionalidade poderosa do NumPy que permite realizar operações entre arrays de diferentes formas e tamanhos de forma eficiente, estendendo automaticamente os arrays menores para corresponder aos maiores.

6. **Integração com outras bibliotecas**: O NumPy é frequentemente usado em conjunto com outras bibliotecas populares de análise de dados em Python, como Pandas, SciPy e Matplotlib, tornando-o parte fundamental do ecossistema de análise de dados em Python.

O NumPy é uma biblioteca essencial para qualquer pessoa que trabalhe com computação científica, análise de dados ou aprendizado de máquina em Python, devido à sua eficiência, funcionalidades matemáticas abrangentes e integração com outras bibliotecas populares.

In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5, 6]

array = np.array(lista)

In [3]:
print(lista)
print(array)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [4]:
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
# Funções Prontas

arr_zeros = np.zeros(10)

print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
print(array[0])

1


In [8]:
array[0] = 9

print(array[0])

9


In [9]:
# Matrizes

matriz_zeros = np.zeros((5, 3))

print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# Operações Matemáticas 

## Notas de ALunos

lista_de_notas = [9.8, 5.6, 7.8, 9.1, 6.5]

notas = np.array(lista_de_notas)

In [17]:
print('Máximo', notas.max())
print('Mínimo', notas.min())
print('Desvio Padrão', notas.std())
print('Média', notas.mean())
print('Posição do Menor', notas.argmin())
print('Posição do Maior', notas.argmax())

Máximo 9.8
Mínimo 5.6
Desvio Padrão 1.5628179676469045
Média 7.76
Posição do Menor 1
Posição do Maior 0
